# Generated by Django 4.2 on 2023-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='body',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='head',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
